### PR TITLE
Issue #96: Update css to fix ribbon scrollbar overlap

### PR DESCRIPTION
**Pull request by paddyw2**
Note: this is a fix for issue #96 

Previously the 'Fork me on GitHub' image overlapped the scrollbar.

This was most notable on Windows, but also existed to some extent on Mac
OS and Linux distros.

Problem: The visible scrollbar did not belong to the body element, and
so the full width of the window was not taken into account by the
position:fixed style of the ribbon.

Solution: The solution was to ensure that only the scrollbar from the
body element is used and visible.

Visually checked on Chrome/Firefox/Safar on Mac OS, Chrome/IE11 on
Windows and Firefox on Debian.

### CODE REVIEW

**Comment by paddyw2** [comment]
On further review, the "top" and "right" changes made to page.groovy are not required to fix the visibility issue. However, they do make the ribbon more similar to the standard style (for example, at https://blog.github.com/2008-12-19-github-ribbons/ and https://brew.sh/).

I can resubmit without the changes to page.groovy if the current style is preferred.

**Comment by paddyw2** [comment]
Upon further review, the "top" and "right" changes made to page.groovy are not required to fix the visibility issue. However, they do make the ribbon more similar to the standard style (for example, at https://blog.github.com/2008-12-19-github-ribbons/ and https://brew.sh/).

I can resubmit without the changes to page.groovy if the current style is preferred.

**Comment by paulk-asert** [comment]
Yes, I believe the top and right changes were to make the ribbon not quite as intrusive into the page. Last time I tried something similar to what you did it mucked up some other pages (perhaps javadoc/groovydoc or docGDK). I'll try to check your change with those.

**Comment by paddyw2** [comment]
Ok sounds good. If you find any issues let me know and I'll take another look.

**Comment by paddyw2** [comment]
I found an issue on the /api.html page, which uses an iframe (maybe one of the pages you were referring to). I'll update if I can make it work on those pages too.

**Comment by paddyw2** [comment]
As mentioned in the commit messages, I realized that the ribbon/scrollbar issue is still and probably will always be an issue on the api.html page due to the iframe. Commit aec2a4a appears to fix the issue most places without iframes, and 9d90b18 is a suggestion on how to make the iframe scrollbars more usable.

**Comment by paulk-asert** [comment]
I have merged your PR into the new repo:
https://github.com/apache/groovy-website/
I haven't finished checking all other pages but I think your suggestion is a step forward and we should adjust from there.

**Comment by paddyw2** [comment]
Sounds good. I think the only part of the original site that could not be kept the same was the perspective effect when showing the side menu. I recreated it relatively closely, but not exactly as it required the "page within a page" styling that I think was causing the ribbon issues.

**Pull request closed without merging**
