### PR TITLE
added the DFW2GUG group and sorted the North American UGs alphabetically

### PR DESCRIPTION
**Pull request by erikweibust**
I lead the DFW Groovy - Grails UG. I'd like to get our group listed on the Groovy site. I also sorted the UGs alphabetically.

### CODE REVIEW

**Comment by glaforge** [comment]
Thanks a lot Erik!

**Comment by erikweibust** [comment]
No problem! I noticed a few other links appeared to be for old UGs that are no longer meeting. Would you like me to clean them up while I'm in this code?

**Comment by glaforge** [comment]
If you're 100% sure they're gone, why not, unless perhaps they have links to their past presentations or something like that.
There are groups like the one in Paris (mine!) where I've been too lazy to run an even recently, but that doesn't mean it's totally dead yet. So I may be reluctant to removing it, for example.

**Comment by erikweibust** [comment]
Good point on the UGs that are just inactive with useful links still pointing to the site. The DC UG is a link that points to a defunct Meetup. No history is preserved on Meetup so I don't see a reason to keep that one. If they start meeting they can add the group and a valid url. I'll submit a PR with that single change if you think makes sense.

**Comment by glaforge** [comment]
Right, if there's no history whatsoever, not really worth keeping it around.

**Pull request merged**
